import pprint
import re  # noqa: F401

import six

class ApplicationIntegrationDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'application': 'AllOfApplicationIntegrationDtoApplication',
        'integration': 'AllOfApplicationIntegrationDtoIntegration'
    }

    attribute_map = {
        'id': 'id',
        'application': 'application',
        'integration': 'integration'
    }

    def __init__(self, id=None, application=None, integration=None):  # noqa: E501
        """ApplicationIntegrationDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._application = None
        self._integration = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if application is not None:
            self.application = application
        if integration is not None:
            self.integration = integration

    @property
    def id(self):
        """Gets the id of this ApplicationIntegrationDto.  # noqa: E501


        :return: The id of this ApplicationIntegrationDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApplicationIntegrationDto.


        :param id: The id of this ApplicationIntegrationDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def application(self):
        """Gets the application of this ApplicationIntegrationDto.  # noqa: E501


        :return: The application of this ApplicationIntegrationDto.  # noqa: E501
        :rtype: AllOfApplicationIntegrationDtoApplication
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this ApplicationIntegrationDto.


        :param application: The application of this ApplicationIntegrationDto.  # noqa: E501
        :type: AllOfApplicationIntegrationDtoApplication
        """

        self._application = application

    @property
    def integration(self):
        """Gets the integration of this ApplicationIntegrationDto.  # noqa: E501


        :return: The integration of this ApplicationIntegrationDto.  # noqa: E501
        :rtype: AllOfApplicationIntegrationDtoIntegration
        """
        return self._integration

    @integration.setter
    def integration(self, integration):
        """Sets the integration of this ApplicationIntegrationDto.


        :param integration: The integration of this ApplicationIntegrationDto.  # noqa: E501
        :type: AllOfApplicationIntegrationDtoIntegration
        """

        self._integration = integration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApplicationIntegrationDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApplicationIntegrationDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
