import pprint
import re  # noqa: F401

import six

class IntegrationFieldDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'label': 'str',
        'required': 'bool',
        'type': 'str'
    }

    attribute_map = {
        'label': 'label',
        'required': 'required',
        'type': 'type'
    }

    def __init__(self, label=None, required=None, type=None):  # noqa: E501
        """IntegrationFieldDto - a model defined in Swagger"""  # noqa: E501
        self._label = None
        self._required = None
        self._type = None
        self.discriminator = None
        if label is not None:
            self.label = label
        if required is not None:
            self.required = required
        if type is not None:
            self.type = type

    @property
    def label(self):
        """Gets the label of this IntegrationFieldDto.  # noqa: E501


        :return: The label of this IntegrationFieldDto.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this IntegrationFieldDto.


        :param label: The label of this IntegrationFieldDto.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def required(self):
        """Gets the required of this IntegrationFieldDto.  # noqa: E501


        :return: The required of this IntegrationFieldDto.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this IntegrationFieldDto.


        :param required: The required of this IntegrationFieldDto.  # noqa: E501
        :type: bool
        """

        self._required = required

    @property
    def type(self):
        """Gets the type of this IntegrationFieldDto.  # noqa: E501


        :return: The type of this IntegrationFieldDto.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this IntegrationFieldDto.


        :param type: The type of this IntegrationFieldDto.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IntegrationFieldDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntegrationFieldDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
