import pprint
import re  # noqa: F401

import six

class TenantListDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dtos': 'list[TenantDto]'
    }

    attribute_map = {
        'dtos': 'dtos'
    }

    def __init__(self, dtos=None):  # noqa: E501
        """TenantListDto - a model defined in Swagger"""  # noqa: E501
        self._dtos = None
        self.discriminator = None
        if dtos is not None:
            self.dtos = dtos

    @property
    def dtos(self):
        """Gets the dtos of this TenantListDto.  # noqa: E501


        :return: The dtos of this TenantListDto.  # noqa: E501
        :rtype: list[TenantDto]
        """
        return self._dtos

    @dtos.setter
    def dtos(self, dtos):
        """Sets the dtos of this TenantListDto.


        :param dtos: The dtos of this TenantListDto.  # noqa: E501
        :type: list[TenantDto]
        """

        self._dtos = dtos

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TenantListDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TenantListDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
