import pprint
import re  # noqa: F401

import six

class UpdateTenantConnectionRequestDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tenant_id': 'str',
        'client_id': 'str',
        'client_secret': 'str',
        'scope': 'str'
    }

    attribute_map = {
        'tenant_id': 'tenantId',
        'client_id': 'clientId',
        'client_secret': 'clientSecret',
        'scope': 'scope'
    }

    def __init__(self, tenant_id=None, client_id=None, client_secret=None, scope=None):  # noqa: E501
        """UpdateTenantConnectionRequestDto - a model defined in Swagger"""  # noqa: E501
        self._tenant_id = None
        self._client_id = None
        self._client_secret = None
        self._scope = None
        self.discriminator = None
        if tenant_id is not None:
            self.tenant_id = tenant_id
        if client_id is not None:
            self.client_id = client_id
        if client_secret is not None:
            self.client_secret = client_secret
        if scope is not None:
            self.scope = scope

    @property
    def tenant_id(self):
        """Gets the tenant_id of this UpdateTenantConnectionRequestDto.  # noqa: E501


        :return: The tenant_id of this UpdateTenantConnectionRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this UpdateTenantConnectionRequestDto.


        :param tenant_id: The tenant_id of this UpdateTenantConnectionRequestDto.  # noqa: E501
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def client_id(self):
        """Gets the client_id of this UpdateTenantConnectionRequestDto.  # noqa: E501


        :return: The client_id of this UpdateTenantConnectionRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this UpdateTenantConnectionRequestDto.


        :param client_id: The client_id of this UpdateTenantConnectionRequestDto.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def client_secret(self):
        """Gets the client_secret of this UpdateTenantConnectionRequestDto.  # noqa: E501


        :return: The client_secret of this UpdateTenantConnectionRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._client_secret

    @client_secret.setter
    def client_secret(self, client_secret):
        """Sets the client_secret of this UpdateTenantConnectionRequestDto.


        :param client_secret: The client_secret of this UpdateTenantConnectionRequestDto.  # noqa: E501
        :type: str
        """

        self._client_secret = client_secret

    @property
    def scope(self):
        """Gets the scope of this UpdateTenantConnectionRequestDto.  # noqa: E501


        :return: The scope of this UpdateTenantConnectionRequestDto.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this UpdateTenantConnectionRequestDto.


        :param scope: The scope of this UpdateTenantConnectionRequestDto.  # noqa: E501
        :type: str
        """

        self._scope = scope

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateTenantConnectionRequestDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateTenantConnectionRequestDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
